version: "3.9"

services:
  isaacsim_env:
    build: ./isaac
    container_name: isaacsim_gpu_gui
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - ACCEPT_EULA=Y
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMNI_KIT_ALLOW_ROOT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ~/Documents/docker_folder/isaacsim_proj:/root/isaacsim_proj
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

  ros2_env:
    build: ./ros2
    container_name: ros2_gpu_gui
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ~/Documents/docker_folder/ros2_proj:/root/ros2_proj
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true